window.ReadyPackersLocales = window.ReadyPackersLocales || {};

window.ReadyPackersLocales.en = {
  meta: {
    pageTitle: 'ReadyPackers IoT - Industrial Monitor',
    htmlLang: 'en',
    locale: 'en-US',
  },
  common: {
    appName: 'ReadyPackers',
    monitorName: 'IoT Monitor',
    emptyDash: '—',
    loading: 'Loading...',
    errorGeneric: 'An error occurred while processing the request.',
    noData: 'No data available',
    noSelection: 'No selection',
    active: 'Active',
    inactive: 'Inactive',
    connected: 'Connected',
    disconnected: 'Disconnected',
    recentDataMissing: 'No recent data',
    update: 'Refresh',
    filter: 'Filter',
    save: 'Save',
    create: 'Create',
    cancel: 'Cancel',
    all: 'All',
    yes: 'Yes',
    no: 'No',
    notAvailable: 'N/A',
    approximateLocation: 'Approximate location',
  },
  language: {
    toggleLabel: 'ES',
    toggleAria: 'Switch language to Spanish',
  },
  public: {
    badge: 'Public view',
    loginButton: 'Login',
    title: 'General machine map',
    subtitle: 'Our devices live.',
    panelKicker: 'Public coverage',
    panelTitle: 'Approximate geographic monitoring',
    panelNote: 'Displayed locations are approximate and zoom is limited for safety.',
    mapLive: 'Visible coverage',
    mapApproximate: 'Approximate location',
    approximateBadge: 'Protected location',
    mapAria: 'Map of registered machines',
    loading: 'Loading public machines...',
    empty: 'There are no visible machines to display right now.',
    summary: 'Showing {count} machines with approximate location.',
    loadError: 'The public map could not be loaded.',
    machineWithoutName: 'Unnamed machine',
    machineWithoutDescription: 'No description',
    ppm: 'Packages per minute',
  },
  auth: {
    title: 'IoT Monitor Access',
    subtitle: 'Sign in with your email and password.',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    loginButton: 'Sign in',
    loggingIn: 'Signing in...',
    forgotPassword: 'I forgot my password',
    forgotSubmit: 'Request reset',
    forgotHaveToken: 'I already have a token',
    backToLogin: 'Back to login',
    resetTokenLabel: 'Reset token',
    resetTokenPlaceholder: 'Paste the token here',
    resetPasswordLabel: 'New password',
    resetPasswordPlaceholder: 'New password',
    resetSubmit: 'Reset password',
    recoveringSession: 'Restoring session...',
    loginRequired: 'Sign in to access the monitor.',
    validating: 'Validating credentials...',
    invalidCredentials: 'Invalid credentials.',
    loginError: 'Could not sign in.',
    authRequired: 'You need to sign in to continue.',
    logoutSuccess: 'Session closed successfully.',
    sessionExpired: 'Your session expired. Please sign in again.',
    sessionAlreadyExpired: 'Your session had already expired.',
  },
  nav: {
    telemetry: 'Telemetry',
    audit: 'Audit',
    admin: 'Administration',
    logout: 'Sign out',
  },
  sidebar: {
    deviceId: 'Device',
    lastUpdate: 'Last update',
  },
  telemetry: {
    pageTitle: 'Telemetry',
    pageSubtitle: 'Continuous process data',
    productsTotal: 'Total Products',
    spAverageWeight: 'SP Average Weight',
    averageWeight: 'Average Weight',
    variable: 'Variable',
    aggregation: 'Aggregation',
    seriesTitle: 'Time series',
    points: '{count} points',
    inactiveVariables: 'No registered variables',
    aggregatedData: 'Aggregated data',
    timestamp: 'Timestamp',
    average: 'Average',
    minimum: 'Minimum',
    maximum: 'Maximum',
    records: 'Record count',
    selectVariableToLoad: 'Select a variable to load data',
    noDevices: 'No devices',
    noVariablesYet: 'No registered variables',
    inactiveValue: 'Inactive',
    activeDeviceSuffix: 'active',
    noAvailableData: 'No data available',
    chartRangeLabel: '{label} - {range}',
    datasetAverage: 'Average',
    datasetMinimum: 'Minimum',
    datasetMaximum: 'Maximum',
    timeRange1Min: '1 minute',
    timeRange5Min: '5 minutes',
    timeRange10Min: '10 minutes',
    timeRange1Hour: '1 hour',
  },
  audit: {
    pageTitle: 'Audit',
    pageSubtitle: 'Configuration and alarm history',
    currentConfig: 'Current machine configuration',
    currentConfigLoading: 'Loading configuration...',
    noConfig: 'No configuration recorded',
    configLoadError: 'Error loading configuration',
    eventType: 'Event type',
    parameter: 'Parameter',
    limit: 'Limit',
    history: 'Event history',
    eventsCount: '{count} events',
    dateTime: 'Date / Time',
    type: 'Type',
    previousValue: 'Previous value',
    newValue: 'New value',
    detail: 'Detail',
    eventsLoading: 'Loading events...',
    noEvents: 'No recorded events',
    eventsLoadError: 'Error loading events',
    eventTypes: {
      SETPOINT_CHANGE: 'SetPoint change',
      STATE_CHANGE: 'State change',
      ALARM_TRIGGER: 'Alarm',
      ALARM_CLEAR: 'Alarm cleared',
      TARE_ACTION: 'Scale tare',
      RECIPE_LOAD: 'Recipe change',
      CALIBRATION: 'Calibration',
    },
    eventBadge: {
      SETPOINT_CHANGE: 'SetPoint',
      STATE_CHANGE: 'State',
      ALARM_TRIGGER: 'Alarm',
      ALARM_CLEAR: 'Alarm OK',
      TARE_ACTION: 'Tare',
      RECIPE_LOAD: 'Recipe',
      CALIBRATION: 'Calibration',
    },
  },
  admin: {
    pageTitle: 'Administration',
    pageSubtitle: 'Clients and machines',
    clients: 'Clients',
    machines: 'Machines',
    name: 'Name',
    email: 'Email',
    initialPassword: 'Initial password',
    role: 'Role',
    status: 'Status',
    action: 'Action',
    clientRole: 'Client',
    statusActive: 'Active',
    statusInactive: 'Inactive',
    createClient: 'Create client',
    ownerClient: 'Owner client',
    visibleName: 'Visible name',
    machineType: 'Type',
    location: 'Location',
    country: 'Country',
    internalLocation: 'Internal machine location',
    latitude: 'Latitude',
    longitude: 'Longitude',
    description: 'Description',
    createMachine: 'Create machine',
    saveMachine: 'Save machine',
    deviceKey: 'deviceKey',
    machineStatusActive: 'Active',
    machineStatusInactive: 'Inactive',
    noClients: 'No registered clients',
    noMachines: 'No registered machines',
    noSensors: 'No variables registered for this machine',
    selectClient: 'Select client',
    plantPlaceholder: 'Main plant',
    countryPlaceholder: 'Colombia',
    mapHelp: 'Click the map to place the pin. These coordinates are internal.',
    descriptionHelp: 'Use this field for internal machine notes. Avoid storing exact addresses.',
    usersLoading: 'Loading...',
    machinesLoading: 'Loading...',
    actions: {
      activate: 'Activate',
      deactivate: 'Deactivate',
      variables: 'Variables',
      locate: 'Locate',
    },
    createClientLoading: 'Creating client...',
    createClientSuccess: 'Client saved.',
    createClientError: 'Could not create the client.',
    createMachineLoading: 'Creating machine...',
    saveMachineLoading: 'Saving machine...',
    createMachineSuccess: 'Machine saved.',
    createMachineError: 'Could not create the machine.',
    loadAdminError: 'Could not load administration.',
    completeActionError: 'Could not complete the action.',
    loadingSensors: 'Loading variables...',
    locateMachineMessage: 'Select the location on the map and save the machine.',
    selectMachineSensors: 'Select a machine to view variables',
  },
  forms: {
    requiredClientName: 'The client name is required.',
    requiredClientEmail: 'The client email is required.',
    requiredClientPassword: 'The initial password is required.',
    roleNotAllowed: 'Role is not allowed from this screen.',
    requiredOwner: 'The owner client is required.',
    requiredMachineName: 'The machine name is required.',
    requiredDeviceKey: 'The deviceKey is required.',
    invalidLatitude: 'Latitude is invalid.',
    invalidLongitude: 'Longitude is invalid.',
    auditPermissionDenied: 'Insufficient permissions for audit.',
    adminPermissionDenied: 'Insufficient permissions for administration.',
  },
  footer: {
    copyright: 'ReadyPackers - IoT Data Acquisition System 2026',
  },
};
